#-------------------------------------------------
#
# Project created by QtCreator 2017-07-06T08:45:29
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets printsupport

TARGET = DS-Asistant
TEMPLATE = app


SOURCES += main.cpp\
    MicroImageDisplay/AddBasicImage.cpp \
    MicroImageDisplay/Layout.cpp \
    MicroImageDisplay/AddBasicGraph.cpp \
    DrawDiagram/barchart.cpp \
    DrawDiagram/qcustomplot.cpp \
    DrawDiagram/scatter.cpp \
    DrawDiagram/testmenu.cpp \
    APP.cpp \
    MicroImageDisplay/Graph.cpp \
    ViewModel.cpp \
    DS/generate.cpp \
    DS/structure.cpp \
    DS/Model.cpp \
    DrawDiagram/TestAsistant.cpp \
    MicroImageDisplay/Transcripton.cpp \
    DrawDiagram/TestCommand.cpp \
    DS/DSCommand.cpp \
    MicroImageDisplay/GraphCommand.cpp\
    src/ValueByIndexDialog.cpp \
    src/AddValuesWidget.cpp \
    src/AddValuesDialog.cpp \
    src/Edge.cpp \
    src/Node.cpp \
    src/TreeManager.cpp \
    src/TreeScene.cpp \
    src/TreeView.cpp \
    src/ViewerWindow.cpp


HEADERS  += \
    MicroImageDisplay/AddBasicImage.h \
    Common.h \
    MicroImageDisplay/Layout.h \
    MicroImageDisplay/AddBasicGraph.h \
    DrawDiagram/Eigen/src/Cholesky/LDLT.h \
    DrawDiagram/Eigen/src/Cholesky/LLT.h \
    DrawDiagram/Eigen/src/Cholesky/LLT_LAPACKE.h \
    DrawDiagram/Eigen/src/CholmodSupport/CholmodSupport.h \
    DrawDiagram/Eigen/src/Core/arch/AltiVec/Complex.h \
    DrawDiagram/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    DrawDiagram/Eigen/src/Core/arch/AVX/Complex.h \
    DrawDiagram/Eigen/src/Core/arch/AVX/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/arch/AVX/PacketMath.h \
    DrawDiagram/Eigen/src/Core/arch/AVX/TypeCasting.h \
    DrawDiagram/Eigen/src/Core/arch/AVX512/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/arch/AVX512/PacketMath.h \
    DrawDiagram/Eigen/src/Core/arch/CUDA/Complex.h \
    DrawDiagram/Eigen/src/Core/arch/CUDA/Half.h \
    DrawDiagram/Eigen/src/Core/arch/CUDA/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/arch/CUDA/PacketMath.h \
    DrawDiagram/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
    DrawDiagram/Eigen/src/Core/arch/CUDA/TypeCasting.h \
    DrawDiagram/Eigen/src/Core/arch/Default/Settings.h \
    DrawDiagram/Eigen/src/Core/arch/NEON/Complex.h \
    DrawDiagram/Eigen/src/Core/arch/NEON/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/arch/NEON/PacketMath.h \
    DrawDiagram/Eigen/src/Core/arch/SSE/Complex.h \
    DrawDiagram/Eigen/src/Core/arch/SSE/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/arch/SSE/PacketMath.h \
    DrawDiagram/Eigen/src/Core/arch/SSE/TypeCasting.h \
    DrawDiagram/Eigen/src/Core/arch/ZVector/Complex.h \
    DrawDiagram/Eigen/src/Core/arch/ZVector/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/arch/ZVector/PacketMath.h \
    DrawDiagram/Eigen/src/Core/functors/AssignmentFunctors.h \
    DrawDiagram/Eigen/src/Core/functors/BinaryFunctors.h \
    DrawDiagram/Eigen/src/Core/functors/NullaryFunctors.h \
    DrawDiagram/Eigen/src/Core/functors/StlFunctors.h \
    DrawDiagram/Eigen/src/Core/functors/TernaryFunctors.h \
    DrawDiagram/Eigen/src/Core/functors/UnaryFunctors.h \
    DrawDiagram/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    DrawDiagram/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    DrawDiagram/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    DrawDiagram/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/GeneralMatrixVector.h \
    DrawDiagram/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/Parallelizer.h \
    DrawDiagram/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    DrawDiagram/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    DrawDiagram/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/SelfadjointProduct.h \
    DrawDiagram/Eigen/src/Core/products/SelfadjointRank2Update.h \
    DrawDiagram/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    DrawDiagram/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/TriangularMatrixVector.h \
    DrawDiagram/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/TriangularSolverMatrix.h \
    DrawDiagram/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    DrawDiagram/Eigen/src/Core/products/TriangularSolverVector.h \
    DrawDiagram/Eigen/src/Core/util/BlasUtil.h \
    DrawDiagram/Eigen/src/Core/util/Constants.h \
    DrawDiagram/Eigen/src/Core/util/DisableStupidWarnings.h \
    DrawDiagram/Eigen/src/Core/util/ForwardDeclarations.h \
    DrawDiagram/Eigen/src/Core/util/Macros.h \
    DrawDiagram/Eigen/src/Core/util/Memory.h \
    DrawDiagram/Eigen/src/Core/util/Meta.h \
    DrawDiagram/Eigen/src/Core/util/MKL_support.h \
    DrawDiagram/Eigen/src/Core/util/NonMPL2.h \
    DrawDiagram/Eigen/src/Core/util/ReenableStupidWarnings.h \
    DrawDiagram/Eigen/src/Core/util/StaticAssert.h \
    DrawDiagram/Eigen/src/Core/util/XprHelper.h \
    DrawDiagram/Eigen/src/Core/Array.h \
    DrawDiagram/Eigen/src/Core/ArrayBase.h \
    DrawDiagram/Eigen/src/Core/ArrayWrapper.h \
    DrawDiagram/Eigen/src/Core/Assign.h \
    DrawDiagram/Eigen/src/Core/Assign_MKL.h \
    DrawDiagram/Eigen/src/Core/AssignEvaluator.h \
    DrawDiagram/Eigen/src/Core/BandMatrix.h \
    DrawDiagram/Eigen/src/Core/Block.h \
    DrawDiagram/Eigen/src/Core/BooleanRedux.h \
    DrawDiagram/Eigen/src/Core/CommaInitializer.h \
    DrawDiagram/Eigen/src/Core/ConditionEstimator.h \
    DrawDiagram/Eigen/src/Core/CoreEvaluators.h \
    DrawDiagram/Eigen/src/Core/CoreIterators.h \
    DrawDiagram/Eigen/src/Core/CwiseBinaryOp.h \
    DrawDiagram/Eigen/src/Core/CwiseNullaryOp.h \
    DrawDiagram/Eigen/src/Core/CwiseTernaryOp.h \
    DrawDiagram/Eigen/src/Core/CwiseUnaryOp.h \
    DrawDiagram/Eigen/src/Core/CwiseUnaryView.h \
    DrawDiagram/Eigen/src/Core/DenseBase.h \
    DrawDiagram/Eigen/src/Core/DenseCoeffsBase.h \
    DrawDiagram/Eigen/src/Core/DenseStorage.h \
    DrawDiagram/Eigen/src/Core/Diagonal.h \
    DrawDiagram/Eigen/src/Core/DiagonalMatrix.h \
    DrawDiagram/Eigen/src/Core/DiagonalProduct.h \
    DrawDiagram/Eigen/src/Core/Dot.h \
    DrawDiagram/Eigen/src/Core/EigenBase.h \
    DrawDiagram/Eigen/src/Core/ForceAlignedAccess.h \
    DrawDiagram/Eigen/src/Core/Fuzzy.h \
    DrawDiagram/Eigen/src/Core/GeneralProduct.h \
    DrawDiagram/Eigen/src/Core/GenericPacketMath.h \
    DrawDiagram/Eigen/src/Core/GlobalFunctions.h \
    DrawDiagram/Eigen/src/Core/Inverse.h \
    DrawDiagram/Eigen/src/Core/IO.h \
    DrawDiagram/Eigen/src/Core/Map.h \
    DrawDiagram/Eigen/src/Core/MapBase.h \
    DrawDiagram/Eigen/src/Core/MathFunctions.h \
    DrawDiagram/Eigen/src/Core/MathFunctionsImpl.h \
    DrawDiagram/Eigen/src/Core/Matrix.h \
    DrawDiagram/Eigen/src/Core/MatrixBase.h \
    DrawDiagram/Eigen/src/Core/NestByValue.h \
    DrawDiagram/Eigen/src/Core/NoAlias.h \
    DrawDiagram/Eigen/src/Core/NumTraits.h \
    DrawDiagram/Eigen/src/Core/PermutationMatrix.h \
    DrawDiagram/Eigen/src/Core/PlainObjectBase.h \
    DrawDiagram/Eigen/src/Core/Product.h \
    DrawDiagram/Eigen/src/Core/ProductEvaluators.h \
    DrawDiagram/Eigen/src/Core/Random.h \
    DrawDiagram/Eigen/src/Core/Redux.h \
    DrawDiagram/Eigen/src/Core/Ref.h \
    DrawDiagram/Eigen/src/Core/Replicate.h \
    DrawDiagram/Eigen/src/Core/ReturnByValue.h \
    DrawDiagram/Eigen/src/Core/Reverse.h \
    DrawDiagram/Eigen/src/Core/Select.h \
    DrawDiagram/Eigen/src/Core/SelfAdjointView.h \
    DrawDiagram/Eigen/src/Core/SelfCwiseBinaryOp.h \
    DrawDiagram/Eigen/src/Core/Solve.h \
    DrawDiagram/Eigen/src/Core/SolverBase.h \
    DrawDiagram/Eigen/src/Core/SolveTriangular.h \
    DrawDiagram/Eigen/src/Core/StableNorm.h \
    DrawDiagram/Eigen/src/Core/Stride.h \
    DrawDiagram/Eigen/src/Core/Swap.h \
    DrawDiagram/Eigen/src/Core/Transpose.h \
    DrawDiagram/Eigen/src/Core/Transpositions.h \
    DrawDiagram/Eigen/src/Core/TriangularMatrix.h \
    DrawDiagram/Eigen/src/Core/VectorBlock.h \
    DrawDiagram/Eigen/src/Core/VectorwiseOp.h \
    DrawDiagram/Eigen/src/Core/Visitor.h \
    DrawDiagram/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    DrawDiagram/Eigen/src/Eigenvalues/ComplexSchur.h \
    DrawDiagram/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    DrawDiagram/Eigen/src/Eigenvalues/EigenSolver.h \
    DrawDiagram/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    DrawDiagram/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    DrawDiagram/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    DrawDiagram/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    DrawDiagram/Eigen/src/Eigenvalues/RealQZ.h \
    DrawDiagram/Eigen/src/Eigenvalues/RealSchur.h \
    DrawDiagram/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    DrawDiagram/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    DrawDiagram/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    DrawDiagram/Eigen/src/Eigenvalues/Tridiagonalization.h \
    DrawDiagram/Eigen/src/Geometry/arch/Geometry_SSE.h \
    DrawDiagram/Eigen/src/Geometry/AlignedBox.h \
    DrawDiagram/Eigen/src/Geometry/AngleAxis.h \
    DrawDiagram/Eigen/src/Geometry/EulerAngles.h \
    DrawDiagram/Eigen/src/Geometry/Homogeneous.h \
    DrawDiagram/Eigen/src/Geometry/Hyperplane.h \
    DrawDiagram/Eigen/src/Geometry/OrthoMethods.h \
    DrawDiagram/Eigen/src/Geometry/ParametrizedLine.h \
    DrawDiagram/Eigen/src/Geometry/Quaternion.h \
    DrawDiagram/Eigen/src/Geometry/Rotation2D.h \
    DrawDiagram/Eigen/src/Geometry/RotationBase.h \
    DrawDiagram/Eigen/src/Geometry/Scaling.h \
    DrawDiagram/Eigen/src/Geometry/Transform.h \
    DrawDiagram/Eigen/src/Geometry/Translation.h \
    DrawDiagram/Eigen/src/Geometry/Umeyama.h \
    DrawDiagram/Eigen/src/Householder/BlockHouseholder.h \
    DrawDiagram/Eigen/src/Householder/Householder.h \
    DrawDiagram/Eigen/src/Householder/HouseholderSequence.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    DrawDiagram/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    DrawDiagram/Eigen/src/Jacobi/Jacobi.h \
    DrawDiagram/Eigen/src/LU/arch/Inverse_SSE.h \
    DrawDiagram/Eigen/src/LU/Determinant.h \
    DrawDiagram/Eigen/src/LU/FullPivLU.h \
    DrawDiagram/Eigen/src/LU/InverseImpl.h \
    DrawDiagram/Eigen/src/LU/PartialPivLU.h \
    DrawDiagram/Eigen/src/LU/PartialPivLU_LAPACKE.h \
    DrawDiagram/Eigen/src/MetisSupport/MetisSupport.h \
    DrawDiagram/Eigen/src/misc/blas.h \
    DrawDiagram/Eigen/src/misc/Image.h \
    DrawDiagram/Eigen/src/misc/Kernel.h \
    DrawDiagram/Eigen/src/misc/lapack.h \
    DrawDiagram/Eigen/src/misc/lapacke.h \
    DrawDiagram/Eigen/src/misc/lapacke_mangling.h \
    DrawDiagram/Eigen/src/misc/RealSvd2x2.h \
    DrawDiagram/Eigen/src/OrderingMethods/Amd.h \
    DrawDiagram/Eigen/src/OrderingMethods/Eigen_Colamd.h \
    DrawDiagram/Eigen/src/OrderingMethods/Ordering.h \
    DrawDiagram/Eigen/src/PardisoSupport/PardisoSupport.h \
    DrawDiagram/Eigen/src/PaStiXSupport/PaStiXSupport.h \
    DrawDiagram/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    DrawDiagram/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    DrawDiagram/Eigen/src/plugins/BlockMethods.h \
    DrawDiagram/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    DrawDiagram/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    DrawDiagram/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    DrawDiagram/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    DrawDiagram/Eigen/src/QR/ColPivHouseholderQR.h \
    DrawDiagram/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    DrawDiagram/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    DrawDiagram/Eigen/src/QR/FullPivHouseholderQR.h \
    DrawDiagram/Eigen/src/QR/HouseholderQR.h \
    DrawDiagram/Eigen/src/QR/HouseholderQR_LAPACKE.h \
    DrawDiagram/Eigen/src/SparseCholesky/SimplicialCholesky.h \
    DrawDiagram/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    DrawDiagram/Eigen/src/SparseCore/AmbiVector.h \
    DrawDiagram/Eigen/src/SparseCore/CompressedStorage.h \
    DrawDiagram/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    DrawDiagram/Eigen/src/SparseCore/MappedSparseMatrix.h \
    DrawDiagram/Eigen/src/SparseCore/SparseAssign.h \
    DrawDiagram/Eigen/src/SparseCore/SparseBlock.h \
    DrawDiagram/Eigen/src/SparseCore/SparseColEtree.h \
    DrawDiagram/Eigen/src/SparseCore/SparseCompressedBase.h \
    DrawDiagram/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    DrawDiagram/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    DrawDiagram/Eigen/src/SparseCore/SparseDenseProduct.h \
    DrawDiagram/Eigen/src/SparseCore/SparseDiagonalProduct.h \
    DrawDiagram/Eigen/src/SparseCore/SparseDot.h \
    DrawDiagram/Eigen/src/SparseCore/SparseFuzzy.h \
    DrawDiagram/Eigen/src/SparseCore/SparseMap.h \
    DrawDiagram/Eigen/src/SparseCore/SparseMatrix.h \
    DrawDiagram/Eigen/src/SparseCore/SparseMatrixBase.h \
    DrawDiagram/Eigen/src/SparseCore/SparsePermutation.h \
    DrawDiagram/Eigen/src/SparseCore/SparseProduct.h \
    DrawDiagram/Eigen/src/SparseCore/SparseRedux.h \
    DrawDiagram/Eigen/src/SparseCore/SparseRef.h \
    DrawDiagram/Eigen/src/SparseCore/SparseSelfAdjointView.h \
    DrawDiagram/Eigen/src/SparseCore/SparseSolverBase.h \
    DrawDiagram/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    DrawDiagram/Eigen/src/SparseCore/SparseTranspose.h \
    DrawDiagram/Eigen/src/SparseCore/SparseTriangularView.h \
    DrawDiagram/Eigen/src/SparseCore/SparseUtil.h \
    DrawDiagram/Eigen/src/SparseCore/SparseVector.h \
    DrawDiagram/Eigen/src/SparseCore/SparseView.h \
    DrawDiagram/Eigen/src/SparseCore/TriangularSolver.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_column_bmod.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_column_dfs.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_Memory.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_pivotL.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_pruneL.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_relax_snode.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_Structs.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLU_Utils.h \
    DrawDiagram/Eigen/src/SparseLU/SparseLUImpl.h \
    DrawDiagram/Eigen/src/SparseQR/SparseQR.h \
    DrawDiagram/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    DrawDiagram/Eigen/src/StlSupport/details.h \
    DrawDiagram/Eigen/src/StlSupport/StdDeque.h \
    DrawDiagram/Eigen/src/StlSupport/StdList.h \
    DrawDiagram/Eigen/src/StlSupport/StdVector.h \
    DrawDiagram/Eigen/src/SuperLUSupport/SuperLUSupport.h \
    DrawDiagram/Eigen/src/SVD/BDCSVD.h \
    DrawDiagram/Eigen/src/SVD/JacobiSVD.h \
    DrawDiagram/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    DrawDiagram/Eigen/src/SVD/SVDBase.h \
    DrawDiagram/Eigen/src/SVD/UpperBidiagonalization.h \
    DrawDiagram/Eigen/src/UmfPackSupport/UmfPackSupport.h \
    DrawDiagram/barchart.h \
    DrawDiagram/menu.h \
    DrawDiagram/qcustomplot.h \
    DrawDiagram/scatter.h \
    DrawDiagram/testmenu.h \
    DrawDiagram/Eigen/Cholesky \
    DrawDiagram/Eigen/CholmodSupport \
    DrawDiagram/Eigen/Core \
    DrawDiagram/Eigen/Dense \
    DrawDiagram/Eigen/Eigen \
    DrawDiagram/Eigen/Eigenvalues \
    DrawDiagram/Eigen/Geometry \
    DrawDiagram/Eigen/Householder \
    DrawDiagram/Eigen/IterativeLinearSolvers \
    DrawDiagram/Eigen/Jacobi \
    DrawDiagram/Eigen/LU \
    DrawDiagram/Eigen/MetisSupport \
    DrawDiagram/Eigen/OrderingMethods \
    DrawDiagram/Eigen/PardisoSupport \
    DrawDiagram/Eigen/PaStiXSupport \
    DrawDiagram/Eigen/QR \
    DrawDiagram/Eigen/QtAlignedMalloc \
    DrawDiagram/Eigen/Sparse \
    DrawDiagram/Eigen/SparseCholesky \
    DrawDiagram/Eigen/SparseCore \
    DrawDiagram/Eigen/SparseLU \
    DrawDiagram/Eigen/SparseQR \
    DrawDiagram/Eigen/SPQRSupport \
    DrawDiagram/Eigen/StdDeque \
    DrawDiagram/Eigen/StdList \
    DrawDiagram/Eigen/StdVector \
    DrawDiagram/Eigen/SuperLUSupport \
    DrawDiagram/Eigen/SVD \
    DrawDiagram/Eigen/UmfPackSupport \
    APP.h \
    MicroImageDisplay/Graph.h \
    ViewModel.h \
    DS/generate.h \
    DS/structure.h \
    DS/Model.h \
    DrawDiagram/TestAsistant.h \
    MicroImageDisplay/Transcripton.h \
    DrawDiagram/TestCommand.h \
    DS/DSCommand.h \
    MicroImageDisplay/GraphCommand.h\
    src/ValueByIndexDialog.h \
    src/AddValuesWidget.h \
    src/AddValuesDialog.h \
    resource.h \
    src/Edge.h \
    src/Node.h \
    src/TreeManager.h \
    src/TreeScene.h \
    src/TreeView.h \
    src/ViewerWindow.h



FORMS    += mainwindow.ui \
    DrawDiagram/testmenu.ui \
    DrawDiagram/scatter.ui \
    DrawDiagram/widget.ui \
    DrawDiagram/barchart.ui \
    MicroImageDisplay/graph.ui \
    ui/valuebyindexdialog.ui \
    ui/addvaluesdialog.ui

DISTFILES += \
    DrawDiagram/img/background.jpg \
    DrawDiagram/img/background.png \
    DrawDiagram/Eigen/CMakeLists.txt \
    LICENSE \
    README

SUBDIRS += \
    DS/DS.pro

RESOURCES += \
    DrawDiagram/image.qrc \
    resources.qrc
